services:
- type: web
  name: webhook-github-action
  runtime: node
  repo: https://github.com/render-examples/webhook-github-action
  branch: create-webhook-github-action
  plan: starter
  envVars:
  - key: RENDER_API_TOKEN
    sync: false
  - key: RENDER_WEBHOOK_SECRET
    sync: false
  region: oregon
  buildCommand: pnpm install && pnpm run build
  startCommand: pnpm run start
